apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-spring-boot-app-k8s-3
  labels:
    backstage.io/kubernetes-id: sample-spring-boot-app-k8s-3
spec:
  params:
    - description: branch
      name: git-revision
      type: string
      default: master
  tasks:
    - name: git-clone
      params:
        - name: URL
          value: 'https://github.com/amintongbackstage/sample-spring-boot-app-k8s-3.git'
        - name: REVISION
          value: $(params.git-revision)
        - name: SSL_VERIFY
          value: 'false'
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: output
          workspace: source-dir
    - name: maven
      params:
        - name: GOALS
          value:
            - test
      runAfter:
        - git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: source-dir
        - name: maven_settings
          workspace: maven_settings
    - name: sonarqube
      params:
        - name: SONAR_HOST_URL
          value: 'https://sonarcloud.io'
        - name: SONAR_PROJECT_KEY
          value: amintongbackstage_sample-spring-boot-app-k8s-3
        - name: SONAR_ORGANIZATION
          value: amintongbackstage
      runAfter:
        - maven
      taskRef:
        kind: Task
        name: sonarqube-scanner
      workspaces:
        - name: source
          workspace: source-dir
        - name: sonar-settings
          workspace: sonar-settings
    - name: get-version
      params:
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - sonarqube
      taskRef:
        kind: Task
        name: maven-get-project-version
      workspaces:
        - name: source
          workspace: source-dir
    - name: s2i-java
      params:
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE
          value: //sample-spring-boot-app-k8s-3:$(tasks.get-version.results.version)
      runAfter:
        - get-version
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: s2i-java
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: source-dir
  workspaces:
    - name: source-dir
    - name: maven_settings
    - name: sonar-settings
