kind: ConfigMap
apiVersion: v1
metadata:
  name: maven-settings
data:
  settings.xml: >-
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">

    </settings>
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sonarqube-secret-token
spec:
  encryptedData:
    login: AgBLD3XJVJwc3EKfo2p0oZydK7Fc/EPYX66W+wAN6RPJvPfbsvIdBXDh+yXC2ihYX7FW5xe8Ci32Sd0qS9o4FsLkSVnCmK3A7ARrorpPetfb+8OegSUZwV3xtSEt6d4bhOpYXlS/sUgmCL/Rb2Je8svOSDT9zExDqioU5mmaaQ4EpReVXeBX5ABQtU2Ix+sxdSYySAzbawOMmT7GTutu0zsdqswAjUoeSCfsZTLZkSlzIlJXG06VwUuOZ9mIgJujFO+GRdgHmZyW01uf745GHmrqeZ73Jc3flgijHqzCnPA1XZqvKqSsYPWXj+5jwFABFw/5TzswLJav1ijzc9cZS7dEoaOfYPem2NJYo82NxAbkiR+drdy+k2vlwAOx4JEvfvO7WQgf82PaIHFGT1DELrg0n9A6JQWyUUkKOyE8WsPJShWoPKPaVf9cxRVP4wvEhlMH3AAnXE3+Yp7orxDCRVGdLCVtVDIqzc/gib7ctQDMycHuWGF4o+3kc/PrFTdpCjIj3W6BjuVvj1vKcQfjSx9JdEBZfTxSTQfbqcGiT9/b/plLqm/BBkMq13uTYKzUQ8ufSL1VXDebquhjiSUyxWz0qE8AMNJRsxDVnenk8h2rhIhEPiV/MSTYkf/LkJq+OtSSwdWbAA5UZo8LVH6BYOfbETIyxKe/SZ7Ti5ebkY9q2Vgn+4hdjLEle4cNL89VsZw65r2C0H3NK9iq
    password: AgCFHU010kLges+LUJXoj+z/aZRJ00247nQnHJEHX5us7bAlgJZ+CDMaJW3xZtHxuNhcdQFu7U9mDJoeqlerIbtJAbzH6hQwbEEMCvW+7e25cQDleXO7PCKJDHChL72ivY+L8K8Kn+0d40HuwH0WIVmio7YJHI8j49JbS+dh0EoZQucI3EbCjgDDdBAZQrR2RKmIqp2IQKJU1LTFVDruY3l5472mCli7A9pWUK2cEDVur2t9zGHQH9GgIz8qvfb9pTUtf4s7kfK6dAiiqeNY8TQEBDQBD+DG/9LjChAGGx4+k+pVH6IVuePnDNM4w4hlc/cN58PH0tZScbgxsfuS1Fnfx5ytTgS8FG6Ptnv6dS6ojBgZx6XfrqPRSoijWmYnhSo5iCF3F6EfcrxCfNyZ5AZ+1bDaoZdx0DCA4NzWc/xg+86LhcBUPN4UMcMhze5dcbXWN/VCJ9kb91u/dX8i7O8y5QMdVyg/AzkLANP6F1wqQbtvc10C+p/uTboOwElSfFowXI9Y18F12di44vbN731jMttNCjthOBcGEpoLwOuCphJFloAFta/UKgY9Bo+1liNq0zShyfh03K9GZIlO8N/D1lZ6rA1nDkkzqlsPTDTCmzwuIE3p6l6q8UmQJ6UmKM199jkfgIgkUsQaQ8gBKAb6GwjRXwCps9kxyyrcPEyyEPucMa4W3ENrw4XL1O4Wqtyo6aLV/QKtKAaqQD3+pO44J4ZiGc4N+Gs/VeZN2DoqdJiC2Ny8n9wGng==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sonarqube-secret-token
    type: Opaque

