kind: ConfigMap
apiVersion: v1
metadata:
  name: maven-settings
data:
  settings.xml: >-
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">

    </settings>
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sonarqube-secret-token
spec:
  encryptedData:
    sonar-project.properties: AgBldQ1I1L0BnNyCgcbgpjrumTkXzYPMzkGeODms28TgY4KO/fhDUasexfqlJ8l5hd958NEX0cYziP/AUHxhk2Dib9N4iUfMHUkRG9UqdbiRLxrSpOrDzwFFL8VaRJa/UGHUgSxKjRN/cPhrKOAoDP+MbDAsTJjLewos2FIoBrdqP6J6EMKTB5BuIpl9ME7/Xr1GtsuTawqP5DK8iccEheiWovhSw/CJOAnt6xWik+GibqybZXqlLZ7CjstI/kZQB5qcs7NaTxTK2J4NlPkA5475oW2u+sVkICG9mYafRDLU9IsmD8uoc3bR15ASwDQ3d3gEkFnCO+f3mZA8nfDbQ61v5jaGqhyjqaKOJAl0ILocB6FJCCAoOmCixi3HnDgcEu3/RkR9IEOw2JVofeVpXY2dEqWt++umEr9us2Fo+NTBX1gsS/hDl2h17QepzaATz3BVSnUuamog3zRC66FDoEmy2ZqOocQ+Mr++5L6ooDUjtIRP8L7cs4w6XAbBFtTLf5Tdp5ddU8SHMfu/2RzNaXJpjxf5QNAK04ix9uqyiuzV2coC/NdB7Zy3cPXqOF/4+TnVMVadZIPaBzYaKXgTq5t/tJFsvpG1NzwgEnazkM7Ii5xLbao2ib6h/Px34HD5AU1zxuG477JGudJY4c6Hw+dx8KzFbXS+joAUmCp5TfYv0PBNvOrdynqeKZ5N+XbO2butBO2NGrCZ8hd+
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sonarqube-secret-token
    type: Opaque
