kind: ConfigMap
apiVersion: v1
metadata:
  name: maven-settings
data:
  settings.xml: >-
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">

    </settings>
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sonarqube-secret-token
spec:
  encryptedData:
    login: AgCuki3QYGU2wdPzVwQYcbiKyriDdzpnFvPlAJfZr8uYft73fpTlkJP4ZOrBN2Zd6EvsKO2P0Etr3FCxjD3X2+ZvmQ5tB2hjnvkskCm52ditPuqVCZKnYrA/abJqOHcpIHSyhehdSomAD/sSLOkKvayBfVJ1jtvElv93AHvB4AY0HW3sWE4jONUcpm+jGxg1ZkLWh5r12wBamVw9RT9Kzz4UfcxAVRoXbiLo5VH5uLTJVwN6sUOuvM433JAfcB2mpJObsMYdOYAudkxVp/CF67s97ZTFIttIGoTeXQ1vJDBZghcSReiVys4O0zZwjH2DzG99IPKw/Y0jzJyixWCOQmOHH7BbFL6HFxRHTbKr36/Go+oVJXa/nbw9JzvbFR1zc2Y8KWrFWw0z1/mskEpMDI+o0ho+ZPwzbfaNHGYKidSKsgGdrzz06CuPfKDCZ6OZ5HqXrZte7OP6BacVnmDC5rGn+E4T3gLExMuCoX0ji5zdajK5TW6pprtCUqPfUL4tmtumJTuVIhE8vqmUiuMWyi8scu3zgKZFgYHgT6oAtfOQhA37yW+hQp5dZ7i30ZkVhfKn/KTgHSEE/CShd8G4Lz4a0NwMKcKl7i0+ns+8JKc6/JCuJ9ZAxD5XbVmAZ/nxPXQtM0ze2aG/gdbRh8wS4zXVz/xsDODc9exEp0Tdhd0tUq7pcbv49K1W2cMRrzV87GggANZwF7j5/6Pv
    password: AgBYk3MrEEjFC9//6qE9DwlkzeI3WST24pI3yVGK6JkGx2Ut0Xwsyf6EAv9F738+pkuTprRxysXB3+Z8fQzLzvYhw7GH5ztZUCfqeXsrH2rhcunrEFcZOf6gSghv4A0Yx1CdQK7vGSnt5lePD1TY8aQ642pu4o8RPtWF/LT/1hRdhlA1OB17rAP0uilooSjN1za27dyGWcIso0PDTtY3pfPA5Qe6b9aCWkzhFuoXqZgd7UxeoBiV1Bh0mvx9l3bA2QERHRD01DcU3sIjO77A2KCL8SCd1qswYla9CsDnXihc/jLf6/Tnf4LaMByPebRvuza/U8z0h9X5AhSqQMnRgtZcboXDgSKWWjktIbrwaHtmvgeTmL9NnsjXM2DkEYv1GQ1zYCar32G6IzUhAoaakO5vnbUUBWDYf8XlLREsWE+uVqO5PpF53ax6nsdNnAU2DGo/fjNRDvuZhoreqNRK5cCGXBmDoCnXPVA6f7gqycmAiQ1ImK8S1c48wTxPn1asJJNlU1R61lVKm39PLhxhxmoBHrFNVJadgwwqnQc32BtMuNHB9aF9MHa9CqLWRudNVwK0Akp4PkZS+dOlcf9XhFotpADEBjiBBEuEWkVROndDYQ1WN7HORp0YN8S+lh6RdVVUmlESqmRxVvZivb4PpVtfhSF+9ClSXKdysUobYxep7N+8/PgctNE3ftFot0GyjXwKWZfkrrvF1diCN46PPK6qUouwzgcIq+Uphkih3YD38fc6/cChWQaPmw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sonarqube-secret-token
    type: Opaque

